name: Publish to GitHub Package Repository

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Pack
      run: dotnet pack -c Release -o out --version-suffix ${GITHUB_RUN_NUMBER}
    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push ./out/*.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/BusHero/index.json 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

